version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rekpero/eliza-spheron-starter:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - OPENROUTER_API_KEY=
      - OPENROUTER_MODEL=meta-llama/llama-3.3-70b-instruct
      - SERVER_PORT=3000
      - SPHERON_PRIVATE_KEY=
      - SPHERON_WALLET_ADDRESS=
      - SPHERON_PROXY_PORT=3040
      - CHARACTER_FILE_URL=https://bafkreigpozbiyu57rzweve4eijfoornm42ljz2lg4jfyygetjajyef6ihy.ipfs.w3s.link/
      - LIGHTHOUSE_API_KEY=
      - TELEGRAM_BOT_TOKEN=
      - COMPUTE_CONFIG=ewogICJuYW1lIjogImVsaXphLXNwaGVyb24tc3RhcnRlciIsCiAgImltYWdlIjogInJla3Blcm8vZWxpemEtc3BoZXJvbi1zdGFydGVyOmxhdGVzdCIsCiAgInBvcnRzIjogWwogICAgewogICAgICAiY29udGFpbmVyUG9ydCI6IDMwMDAsCiAgICAgICJzZXJ2aWNlUG9ydCI6IDMwMDAKICAgIH0KICBdLAogICJlbnYiOiBbXSwKICAiY29tcHV0ZVJlc291cmNlcyI6IHsKICAgICJjcHUiOiA0LAogICAgIm1lbW9yeSI6ICI4R2kiLAogICAgInN0b3JhZ2UiOiAiMTAwR2kiCiAgfSwKICAiZHVyYXRpb24iOiAiMWgiLAogICJtb2RlIjogInByb3ZpZGVyIiwKICAicmVkZXBsb3lUaHJlc2hvbGQiOiA2MDAwMDAsCiAgImRlcGxveU1vbml0b3JJbnRlcnZhbCI6IDMwMDAwCn0
