version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rekpero/eliza-spheron-starter:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - OPENROUTER_API_KEY=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
      - OPENROUTER_MODEL=meta-llama/llama-3.3-70b-instruct
      - TWITTER_POLL_INTERVAL=1
      - SERVER_PORT=3000
      - SPHERON_PRIVATE_KEY=
      - SPHERON_WALLET_ADDRESS=
      - SPHERON_PROXY_PORT=3040
      - CHARACTER_FILE_URL=https://bafkreidnbcxbs7oco62fqrcc5z5del4po3b7gef2l5keikwey46gnmqqia.ipfs.w3s.link/
      # - LIGHTHOUSE_API_KEY=e915cb3e.5d7a45a762d5448da8c1fcfcb628a30e
