version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rekpero/eliza-spheron-starter:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - OPENROUTER_API_KEY=
      - OPENROUTER_MODEL=meta-llama/llama-3.3-70b-instruct
      - TWITTER_POLL_INTERVAL=1
      - SERVER_PORT=3000
      - SPHERON_PRIVATE_KEY=
      - SPHERON_WALLET_ADDRESS=
      - SPHERON_PROXY_PORT=3040
      - CHARACTER_FILE_URL=https://bafkreigpozbiyu57rzweve4eijfoornm42ljz2lg4jfyygetjajyef6ihy.ipfs.w3s.link/
      - LIGHTHOUSE_API_KEY=
      - TELEGRAM_BOT_TOKEN=
