version: "1.0"

services:
  eliza-spheron-starter:
    image: rekpero/eliza-spheron-starter:latest
    pull_policy: Always
    expose:
      - port: 3000
        as: 3000
        to:
          - global: true
    env:
      - OPENROUTER_API_KEY=
      - OPENROUTER_MODEL=meta-llama/llama-3.3-70b-instruct
      - SERVER_PORT=3000
      - SPHERON_PRIVATE_KEY=
      - SPHERON_WALLET_ADDRESS=
      - SPHERON_PROXY_PORT=3040
      - LIGHTHOUSE_API_KEY=
      - CHARACTER_FILE_URL=https://bafkreigpozbiyu57rzweve4eijfoornm42ljz2lg4jfyygetjajyef6ihy.ipfs.w3s.link/
      - TELEGRAM_BOT_TOKEN=
      - COMPUTE_CONFIG=ewogICJuYW1lIjogImVsaXphLXNwaGVyb24tc3RhcnRlciIsCiAgImltYWdlIjogInJla3Blcm8vZWxpemEtc3BoZXJvbi1zdGFydGVyOmxhdGVzdCIsCiAgInBvcnRzIjogWwogICAgewogICAgICAiY29udGFpbmVyUG9ydCI6IDMwMDAsCiAgICAgICJzZXJ2aWNlUG9ydCI6IDMwMDAKICAgIH0KICBdLAogICJlbnYiOiBbXSwKICAiY29tcHV0ZVJlc291cmNlcyI6IHsKICAgICJjcHUiOiA0LAogICAgIm1lbW9yeSI6ICI4R2kiLAogICAgInN0b3JhZ2UiOiAiMTAwR2kiCiAgfSwKICAiZHVyYXRpb24iOiAiMWgiLAogICJtb2RlIjogInByb3ZpZGVyIiwKICAicmVkZXBsb3lUaHJlc2hvbGQiOiA2MDAwMDAsCiAgImRlcGxveU1vbml0b3JJbnRlcnZhbCI6IDMwMDAwCn0
profiles:
  name: eliza-spheron-starter
  duration: 14min
  mode: provider
  tier:
    - community
    - secure
  compute:
    eliza-spheron-starter:
      resources:
        cpu:
          units: 8
        memory:
          size: 16Gi
        storage:
          - size: 100Gi
  placement:
    westcoast:
      pricing:
        eliza-spheron-starter:
          token: CST
          amount: 1

deployment:
  eliza-spheron-starter:
    westcoast:
      profile: eliza-spheron-starter
      count: 1
